#!/bin/sh
#
# NeoStats Crontab v2.1
#
# change this to the mail address to mail output to:
MAIL=me
# change this to the directory you run your ircd from:
dir="/home/services/NeoStats2.0.7/"

# change this to the name of your ircd's file in that directory:
ircdexe="stats"

# I wouldn't touch this if I were you.
ircdname="neostats.pid"

########## you probably don't need to change anything below here ##########

cd $dir
  ircdpid=`cat $ircdname`
  `kill -9 $ircdpid`
  rm -f $ircdname
  ./$ircdexe
