# Script to generate SVN version information

# Grab the revision from "svn info"
id=`svn info |grep 'Revision:'`
id=`echo $id |sed 's/.* Revision: \(.*\) .* Exp .*/\1/'`
# For debugging
#echo "$id"

# Variable to hold status of current version.h
# 0 : OK, 1 : needs update, 2 : needs creating
versionok=0

# Test current version header against the current revision
if test -r version.h
then
	idold=`sed -n 's/^#define NEOSTATS_REVISION \"\(.*\)\"/\1/p' < version.h`
#	For debugging
#	echo "$idold"
	if [ "$idold" = "$id" ] 
	then 
		# version header matches current revision
		echo "version.h up to date"
	else
		# version header needs updating to current revision
		echo "Updating version.h..."
		versionok=1
	fi
else
	# version header not found
	echo "Creating version.h..."
	versionok=2
fi

# For debugging
#echo $versionok

# Create or update version header to the current revision
if [ $versionok != 0 ] 
then
cat >version.h <<EOF
/*
 * This file is generated by version.sh. DO NOT EDIT. 
 */

#define NEOSTATS_REVISION "$id"

EOF

fi
